[project]
name = "antsaibot"
version = "0.1.0"
description = "Ants AI Challenge Python Bot and Engine"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "colorama",
    "pytest"
]

[tool.uv]
# Add UV-specific configuration here if needed

[build-system]
requires = ["uv"]
build-backend = "uv.build" 